### ISSUE TITLE
Error: Cannot read property extend of undefined

### ISSUE THREAD

**Issue by jabhishek** [jaylaw81/generator-react-sdp#1]
Hi,

On running the generator and just after selecting the component name, I am getting the below error. It looks like you will have to use lodash or underscore rather than using the existing extend method. The error is on line 37 in index.js.

Thanks,
Abhi.

![image](https://cloud.githubusercontent.com/assets/1830537/10007852/cdeab980-60c0-11e5-9119-3de84377b729.png)

**Comment by jaylaw81** [comment]
@jabhishek : Thanks for finding this. This has been fixed with latest commit to master. https://github.com/jaylaw81/generator-react-jspmio/commit/a04edfae107753db284d59fb395e58aa44ab4653

**Comment by jabhishek** [comment]
Thanks for fixing this. Abhi.
